### ISSUE TITLE
On LinuxMint 19.3 Rivendell 3.2.1int3 compile error

### ISSUE THREAD

**Issue by dancebeatfm** [ElvishArtisan/rivendell#529]
The latest git with MusicBrainz support doesn't compile on LinuxMint 19.3.

Package: libmusicbrainz5-dev
Version: 5.1.0+git20150707-7

Package: libdiscid-dev
Version: 0.6.2-2

Package: libcoverart-dev
Version: 1.0.0+git20150706-6

./configure command has no errors everything is fine, but make command stops at

CXX      cae_server.o
moc-qt4 cae.h -o moc_cae.cpp
moc-qt4 cae_server.h -o moc_cae_server.cpp
  CXX      moc_cae.o
  CXX      moc_cae_server.o
  CXXLD    caed
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::ArtistCredit() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::~CQuery()'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::ISRCList() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CList::Item(int) const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::CQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::Title[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CRelease'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CNameCredit::JoinPhrase[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::Title[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::LastErrorMessage[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::MediumList() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CNameCredit::Artist() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CLabelInfo::Label() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CLabel::Name[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMetadata::Release() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CNameCredit'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMetadata::Disc() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CTrack::Recording() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CMedium'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMedium::Format[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CISRC::ID[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CDisc::ReleaseList() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::Barcode[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMediumList::~CMediumList()'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CLabelInfo'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CArtistCredit::NameCreditList() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::ID[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::LastHTTPCode() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMedium::TrackList() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::FetchFront(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::LastErrorMessage[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::MediaMatchingDiscID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::CCoverArt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CArtist::Name[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CList::NumItems() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::Date[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CTrack'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::LabelInfoList() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::~CCoverArt()'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::LastResult() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::ID[abi:cxx11]() const'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CISRC'
/home/avg/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CEntity'
collect2: error: ld returned 1 exit status
Makefile:481: recipe for target 'caed' failed
make[1]: *** [caed] Error 1
make[1]: Leaving directory '/home/avg/rivendell/cae'
Makefile:519: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ElvishArtisan** [comment]
Please try this again, this time using 'make V=1' instead of just 'make'. (It will still fail, but you should get a lot more information regarding why).

**Comment by dancebeatfm** [comment]
> Please try this again, this time using 'make V=1' instead of just 'make'. (It will still fail, but you should get a lot more information regarding why).

Thanks for reply.

Here is the output of make V=1

make[1]: Entering directory '/home/avg/test/rivendell/cae'
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT cae.o -MD -MP -MF .deps/cae.Tpo -c -o cae.o cae.cpp
mv -f .deps/cae.Tpo .deps/cae.Po
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT cae_alsa.o -MD -MP -MF .deps/cae_alsa.Tpo -c -o cae_alsa.o cae_alsa.cpp
cae_alsa.cpp: In member function ‘bool MainObject::alsaLoadRecord(int, int, int, int, int, int, QString)’:
cae_alsa.cpp:1042:8: warning: ignoring return value of ‘int chown(const char*, __uid_t, __gid_t)’, declared with attribute warn_unused_result [-Wunused-result]
   chown((const char *)wavename,rd_config->uid(),rd_config->gid());
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/cae_alsa.Tpo .deps/cae_alsa.Po
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT cae_hpi.o -MD -MP -MF .deps/cae_hpi.Tpo -c -o cae_hpi.o cae_hpi.cpp
mv -f .deps/cae_hpi.Tpo .deps/cae_hpi.Po
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT cae_jack.o -MD -MP -MF .deps/cae_jack.Tpo -c -o cae_jack.o cae_jack.cpp
cae_jack.cpp: In member function ‘bool MainObject::jackLoadRecord(int, int, int, int, int, int, QString)’:
cae_jack.cpp:1013:8: warning: ignoring return value of ‘int chown(const char*, __uid_t, __gid_t)’, declared with attribute warn_unused_result [-Wunused-result]
   chown((const char *)wavename,rd_config->uid(),rd_config->gid());
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/cae_jack.Tpo .deps/cae_jack.Po
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT cae_server.o -MD -MP -MF .deps/cae_server.Tpo -c -o cae_server.o cae_server.cpp
mv -f .deps/cae_server.Tpo .deps/cae_server.Po
moc-qt4 cae.h -o moc_cae.cpp
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT moc_cae.o -MD -MP -MF .deps/moc_cae.Tpo -c -o moc_cae.o moc_cae.cpp
mv -f .deps/moc_cae.Tpo .deps/moc_cae.Po
moc-qt4 cae_server.h -o moc_cae_server.cpp
g++ -DPACKAGE_NAME=\"rivendell\" -DPACKAGE_TARNAME=\"rivendell\" -DPACKAGE_VERSION=\"3.2.1int3\" -DPACKAGE_STRING=\"rivendell\ 3.2.1int3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"rivendell\" -DVERSION=\"3.2.1int3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_VORBIS=1 -DHAVE_FLAC=1 -DHAVE_MP4_LIBS=1 -DHAVE_MAD=1 -DHAVE_TWOLAME=1 -DHAVE_LAME=1 -DJACK=yes -DALSA=yes -DSRC=yes -DHAVE_FLAC_METADATA=yes -I.  -Wall -I../lib -I../rdhpi -Wno-strict-aliasing -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/libxml2 -I/usr/include/neon -DQT3_SUPPORT -I/usr/include/Qt3Support   -g -O2 -MT moc_cae_server.o -MD -MP -MF .deps/moc_cae_server.Tpo -c -o moc_cae_server.o moc_cae_server.cpp
mv -f .deps/moc_cae_server.Tpo .deps/moc_cae_server.Po
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2   -o caed cae.o cae_alsa.o cae_hpi.o cae_jack.o cae_server.o moc_cae.o moc_cae_server.o -lm -lpthread -lrd -lcurl -lid3 -ltag -lFLAC -lFLAC++ -lsndfile -lsamplerate -lcdda_interface -lcdda_paranoia -lcrypt -ldl -lpam -lSoundTouch -lcrypto -lasound -ljack -lsamplerate -lvorbisfile -lvorbisenc -lQtXml -lQt3Support -lQtGui -lQtNetwork -lQtSql -lQtCore -ldiscid -lmusicbrainz5 -lcoverart -lQt3Support -L../lib -L../rdhpi
libtool: link: g++ -g -O2 -o .libs/caed cae.o cae_alsa.o cae_hpi.o cae_jack.o cae_server.o moc_cae.o moc_cae_server.o  -lm -lpthread /home/avg/test/rivendell/lib/.libs/librd.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libid3.so -ltag -lFLAC -lFLAC++ -lsndfile -lcdda_interface -lcdda_paranoia -lcrypt -ldl -lpam -lSoundTouch -lcrypto -lasound -ljack -lsamplerate /usr/lib/x86_64-linux-gnu/libvorbisfile.so /usr/lib/x86_64-linux-gnu/libvorbisenc.so -lQtXml -lQtGui -lQtNetwork -lQtSql -lQtCore -ldiscid -lmusicbrainz5 -lcoverart -lQt3Support -L../lib -L../rdhpi -pthread
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::ArtistCredit() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::~CQuery()'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::ISRCList() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CList::Item(int) const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::CQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::Title[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CRelease'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CNameCredit::JoinPhrase[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::Title[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::LastErrorMessage[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::MediumList() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CNameCredit::Artist() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CLabelInfo::Label() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CLabel::Name[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMetadata::Release() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CNameCredit'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMetadata::Disc() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CTrack::Recording() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CMedium'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMedium::Format[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CISRC::ID[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CDisc::ReleaseList() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::Barcode[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMediumList::~CMediumList()'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CLabelInfo'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CArtistCredit::NameCreditList() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::ID[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::LastHTTPCode() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CMedium::TrackList() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::FetchFront(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::LastErrorMessage[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::MediaMatchingDiscID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::CCoverArt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CArtist::Name[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CList::NumItems() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::Date[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CTrack'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::LabelInfoList() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `CoverArtArchive::CCoverArt::~CCoverArt()'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::LastResult() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::ID[abi:cxx11]() const'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CISRC'
/home/avg/test/rivendell/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CEntity'
collect2: error: ld returned 1 exit status
Makefile:481: recipe for target 'caed' failed
make[1]: *** [caed] Error 1
make[1]: Leaving directory '/home/avg/test/rivendell/cae'
Makefile:519: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ElvishArtisan** [comment]
Thanks.

I ended up building a Mint 19.3 install here, and was able to reproduce the exact same error. After a lot of experimentation, I ended up removing the pre-packaged MusicBrainz libraries, downloading the source tarballs for those three components and building/installing them directly on the target system. Current Rivendell 'master' then builds perfectly. Thus, I've come to the conclusion that one or more of the three Musicbrainz-sourced Debian packages are corrupt.
