### ISSUE TITLE
MusicBrainz

### ISSUE THREAD

**Issue by wpope** [ElvishArtisan/rivendell#578]
I am trying to build on Ubuntu 18.04
rivendell build rivendell-3.3.0int0
have installed:
  libmusicbrainz-discid-perl (0.04-1)
  libmusicbrainz5-2 (5.1.0+git20150707-7)
  libmusicbrainz5-dev (5.1.0+git20150707-7)
  libmusicbrainz5cc2v5 (5.1.0+git20150707-7)
  libwebservice-musicbrainz-perl (0.93-1.1)
  libmusicbrainz5-doc (5.1.0+git20150707-7)

moc-qt4 cae_server.h -o moc_cae_server.cpp
  CXX      moc_cae_server.o
  CXXLD    caed
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRelease::ArtistCredit() const'
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::~CQuery()'
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::ISRCList() const'
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CList::Item(int) const'
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CQuery::CQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `MusicBrainz5::CRecording::Title[abi:cxx11]() const'
/home/ciam/dev/rivendell-3.3.0int0/lib/.libs/librd.so: undefined reference to `typeinfo for MusicBrainz5::CRelease'
...

Walter

**Comment by dancebeatfm** [comment]
Hello wpope, I think you're issue is the same as this https://github.com/ElvishArtisan/rivendell/issues/529#issue-569459037

**Comment by wpope** [comment]
Thank you very much.  I was suspicious of the musicbrainz build.
